### ISSUE TITLE
1.0 Release Checklist

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#1329]
I wanted to collect all last-minute tasks we need to accomplish when we publish 1.0. Mostly these changes relate to `@chakra-ui/core@latest` pointing to `1.0` and https://chakra-ui.com being updated to point to the v1 docs. We'll need to update various parts of our docs/pipeline to make sure this happens.

- [x] Add Vercel v0.chakra-ui.com alias to existing deployment for chakra-ui.com
- [x] Update `alias` in `vercel.json` to https://chakra-ui.com/
- [x] Replace https://chakra-ui.com/ with https://v0.chakra-ui.com/ throughout the project
- [x] Replace https://next.chakra-ui.com/ with https://chakra-ui.com/ throughout the project
- [x] Add link to/note about outdated v0 docs somewhere in the v1 docs (?)
- [x] Replace `1.0.0-next.#`-specific versioning with base package names throughout the project (`@chakra-ui/core` instead of `@chakra-ui/core@next`)
- [ ] Update `EDIT_URL` to point to `master` in `next.config.js`
- [x] Update `version`/`publish` scripts to no longer use `rc`

**Comment by segunadebayo** [comment]
I'd suggest we leave the docs as is, and make `v1.chakra-ui.com` till it's very stable.

**Comment by with-heart** [comment]
@segunadebayo I'm going back and forth on that. It makes sense to not confuse users on `<=0.8` but I think it might cause problems for new users post-1.0 launch who may not catch that the main site doesn't have the docs they need. Not sure!

**Comment by fr3fou** [comment]
Is the 1.0 release date public anywhere?

**Comment by with-heart** [comment]
@fr3fou There is no date. We had been in our alpha `next` versions but have now moved to release candidates (`rc.0` currently) since things are now mostly stable. Barring any unforseen circumstances, the api in `rc.0` is the one that will exist in 1.0 though.

There are still a number of things to complete before we feel comfortable fully releasing 1.0 but we're getting there.

**Comment by fr3fou** [comment]
So is it safe for me to use `next` without any issues?

**Comment by with-heart** [comment]
Depends on how you define "safe" and "without any issues" 😆 

It's in a fairly stable place but it isn't entirely bug-free yet, which is why it's not `1.0.0` yet. You should be able to use it without problems, but I can't promise you won't run into anything.

**Comment by maxwaiyaki** [comment]
> I'd suggest we leave the docs as is, and make `v1.chakra-ui.com` till it's very stable.

What about redirecting [https://v1.chakra-ui.com/](https://v1.chakra-ui.com/) to [https://next.chakra-ui.com/](https://next.chakra-ui.com/)? It's currently broken.

**Comment by chhuang** [comment]
Couldn't find this anywhere but just curious, what's the reason of moving the docs from Gatsby to Next?

**Comment by with-heart** [comment]
@vonwao It won't matter much longer but putting it in the README for the time being is a good idea. I'll do that

**Comment by chhuang** [comment]
> > what's the reason of moving the docs from Gatsby to Next
> 
> @chhuang I don't know the answer for sure but I believe Next.js is more flexible, especially if you want to server-render dynamic content (Gatsby basically generates a static site), and maybe if you want to show off advanced/dynamic features of chakra-ui and you want it SSR then next.js will be better. Lots of comparison articles on google.

I understand the difference between the two, I was just curious and wanted to understand better the reasoning behind the switch.

**Comment by ianwalter** [comment]
I really like the new docs site. It's too bad it's not a framework itself. 

Also, is there any information on the upgrade steps to 1.0? Maybe I just missed it, but I'm having a hard time doing that.

**Comment by ljosberinn** [comment]
we have a migration guide here: https://next.chakra-ui.com/docs/migration :)

**Comment by ianwalter** [comment]
Wow I am blind today, thanks @ljosberinn

**Comment by nghiepit** [comment]
I think We should be released `rc` version more frequently.

The `1.0` version has many problems with performance. Example `Popover`.

**Comment by ljosberinn** [comment]
What performance problems are you seeing?

**Comment by nghiepit** [comment]
@ljosberinn 
One of the Popover issue https://github.com/chakra-ui/chakra-ui/issues/2091

**Comment by ianstormtaylor** [comment]
Any updates on the `1.0` release date? Been using `0.8` and there are handful of little bugs throughout the core library. I've searched through issues and they've been closed because they are fixed in `1.0` (which is totally reasonable) but I'm unsure if it's stable enough to use yet?

FWIW, I'd be personally more interested in a smaller `0.9` that didn't seek to completely nail the API (I'm fine with breaking changes over time if they are for the better) but fixed a lot of the little annoyances, than to bundle it up into a much larger `1.0` that may take a long time to ship.

**Comment by MarcLongJoyride** [comment]
^ Same. Our company Joyride.com is ready to completely switch over to Chakra but we are simply waiting on Chakra to go to 1.0 before we commit.

**Comment by potty** [comment]
Will Chakra UI 1.0 use Emotion 10 or 11?

**Comment by ljosberinn** [comment]
11 :)

**Comment by hutber** [comment]
Just wondering if we are going to push this latest release to NPM? Thanks GUys

**Comment by ljosberinn** [comment]
It's been released on friday!

**Comment by hutber** [comment]
I just saw in the new docs that its been renamed to `/react`thank you :) It was a bit of a thing I missed though, as I was already on version RC's.

Thanks again :D
