### ISSUE TITLE
Create official Chakra UI Storybook addon

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#2694]
The goal of this issue is to create an official Storybook preset addon for Chakra UI. Offering an official preset means that users need only install the preset to quickly get up and running with Chakra inside Storybook.

# Tasks

- [ ] Automatically decorate stories with `ChakraProvider`
- [ ] Enable customization of `ChakraProvider`
	- [ ] Custom `theme`
	- [ ] `resetCSS`, `portalZIndex`, etc. props
- [ ] Handle overriding Storybook `emotion` package conflicts? (see https://github.com/storybookjs/storybook/issues/13114 and #2527 for more context)
- [ ] Dogfood the preset package for our own internal Storybook setup (the ultimate test!)

# Possible stretch goals

- Add a color mode toggle button to the UI Toolbar to allow users to quickly switch color mode of the current story

**Comment by with-heart** [comment]
As much as I'd like for this to be a thing, I'm gonna close it for the time being as I don't think any of us have any intention of working on it soon. If anyone would like to pick this up, feel free to respond with a plan and we can re-open.

**Comment by with-heart** [comment]
I'd like to tackle this sometime this week. Going to reopen.

**Comment by nftgeek** [comment]
Hello @with-heart  I'm new to Chakra but I'd love to see ChakraUI storybook!  is it ready?

**Comment by Adrian-Benavente** [comment]
Looking forward to it! Thanks!

**Comment by segunadebayo** [comment]
I'm going to close this for now.

Please follow the progress here: https://github.com/chakra-ui/chakra-ui/pull/3586 to get updates.

**Comment by TimKolberger** [comment]
**We just released `@chakra-ui/storybook-addon`:**

Use the official Storybook Addon for Chakra UI to configure Storybook to automatically wrap your stories with the `<ChakraProvider />` and add a color mode toggle.

## Installation

```bash
yarn add -D @chakra-ui/storybook-addon
yarn add @chakra-ui/icons
```

or 

```bash
npm i -D @chakra-ui/storybook-addon
npm i @chakra-ui/icons
```

## Usage

Add the addon to your configuration in `.storybook/main.js`:

```js
module.exports = {
  addons: ['@chakra-ui/storybook-addon'],
}
```

You can specify global parameters for the addon in .storybook/preview.js. These options are the same as the props to ChakraProvider (without children).

```js
// .storybook/preview.js

const theme = require('../path/to/your/theme')

export const parameters = {
  chakra: {
    theme,
  },
}
```

**Comment by simontaisne** [comment]
Looking good @TimKolberger, thanks 👍 Just noticed that in order to make it work there's a required dependency to `@chakra-ui/icons`. It doesn't build without adding this dependency explicitly. Should I open an issue to track that?

**Comment by Todilo** [comment]
Anyone got this addon working?


I get errors in the Docs page.
```
export var DocsWrapper = styled.div(function (_ref5) {
  var theme = _ref5.theme;
  return _defineProperty({
    background: theme.background.content,
    display: 'flex',
    justifyContent: 'center',
    padding: '4rem 20px',
    minHeight: '100vh',
    boxSizing: 'border-box'
  }, "@media (min-width: ".concat(breakpoint, "px)"), {});
```
theme is undefined here.

This can be found in this repo:
https://github.com/Todilo/storybook-chakra-ui-addon-error

**Comment by jthetzel** [comment]
Thanks, @Todilo ! Don't know why that works either. Here is the `./storybook/main.js` that works for me after a minimal storybook, typescript, chakra-ui, and chakra-ui-storybook-add-on install:

```
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/preset-create-react-app',
    '@chakra-ui/storybook-addon'
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-webpack5'
  },
  webpackFinal: async config => {
    delete config.resolve.alias['emotion-theming']
    delete config.resolve.alias['@emotion/styled']
    delete config.resolve.alias['@emotion/core']

    return config
  }
}
```
