### ISSUE TITLE
[Icon] Docs inconsistencies

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui#998]
@beforan posted some notes in https://github.com/chakra-ui/chakra-ui/issues/906#issuecomment-650189674 detailing some inconsistencies in the `Icon` docs for 1.0. This issue tracks the effort needed to clean up these inconsistencies.

- [x] Replace existing `Usage` section in `website/docs/components/icon.mdx` with a better explanation of the purpose of `Icon` in 1.0
- [x] Document `fallbackIcon` behavior (#1115)
- [x] Demonstrate creating an `Icon` using the component rather than `createIcon` (#1115)
- [x] Note the differences between `Icon` and `createIcon`
- [x] Remove references to `name` prop that no longer exists (partially completed in #988 but some references remain)
- [x] Remove references to `theme.icons` object that is no longer used (partially completed in #988 but some references remain)
- [x] Add `createIcon` docs
- [x] Add migration notes for `Icon`
- [x] Rename `size` prop to `boxSize` prop for all icons in docs (#1115)
- [x] Document `<Icon as={CustomIcon} />`

**Comment by segunadebayo** [comment]
@with-heart, I see you have a pretty good idea of the `Icon` component. Want to jump on this?

**Comment by with-heart** [comment]
@segunadebayo On it!

**Comment by with-heart** [comment]
I have an unfinished PR that should resolve my remaining concerns about `Icon` docs. I'll try to get that opened later today

**Comment by tomhicks** [comment]
Hi there.

Rather than open a new issue, thought I'd drop this here.

Using <Button leftIcon={<Icon as={SomeSvg} />}/>

It seems like the button should pass through some size-dependent boxSize to the icon, but it doesn't, which leaves the icons having a size of "1em" which makes them look smaller than I would expect.

Also, for the life of me I can't seem to get the Icon component to pick up any styles from the `chakra/components/index` file, even after I've added an Icon block to it. Is there some reason the Icon theme config isn't in the default? Is it just WIP?

Cheers
